#!/bin/bash
#echo Best School\n > \\\\*$\\?\\*\\*\\*\\*\\*:\)
#echo Best School\n > "''\*\\'"Best School"\'\\*$\?\*\*\*\*\*:)"
#touch '\*\\''"Best School"\''\\*$\?\*\*\*\*\*:)'/n
echo "Best School" \n> '\*'\\'"Best School"'\''\\*$\?\*\*\*\*\*:)'
